name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile --tag sklearn
           docker run --name buildcontainer sklearn
    - name: Copy container build output
      run:
        docker cp buildcontainer:/data/sklearn apkout
    - name: Copy generated apk
      uses: actions/upload-artifact@v2
      with:
        name: sklearn
        path: ${{ github.workspace }}/apkout/
